
development:
  adapter: postgresql
  encoding: unicode
  database: photogur2_development
  pool: 5
  username:
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: photogur2_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: photogur2_production
  pool: 5
  username:
  password: 